spring.application.name=tau-survey-system
# Database Configuration
spring.datasource.url=jdbc:h2:mem:survey_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enabling database preview in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Azure AD Configuration
# Replace {TENANT_ID} with your actual Azure Tenant ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/{TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/{TENANT_ID}/discovery/v2.0/keys

# Lines for testing and debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG