spring.application.name=tau-survey-system

# Ustawienia bazy H2
spring.datasource.url=jdbc:h2:mem:survey_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# W??czenie podgl?du bazy w przegl?darce
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



# Konfiguracja Azure AD
# Zast?p {TENANT_ID} naszym rzeczywistym indentyfikatorem Azure Tenant ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/{TENANT_ID}/v2.0
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/{TENANT_ID}/discovery/v2.0/keys


# Linijki do testowania i debugowania
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG